// // 'use-client'
// import type { Metadata } from "next";
// import RQProviders from "@/utils/provider";
// import { Poppins, Inter } from "next/font/google";
// // import { CookiesProvider } from 'react-cookie';
// import "./globals.css";
// const inter = Inter({ subsets: ["latin"] });
// const poppins = Poppins({ subsets: ["latin"], weight: ["400", "900"], });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//         <RQProviders>
//           <body className={poppins.className}>{children}</body>
//         </RQProviders>
//     </html>
//   );
// }


import type { Metadata } from 'next'
import { Poppins, Inter, Nunito_Sans } from 'next/font/google'
import './globals.css'
import RQProviders from '@/utils/provider'
import { Providers } from './Provider'
import { ToastContainer, toast } from "react-toastify";
// import '~react-toastify/dist/ReactToastify.min.css';
 import "react-toastify/dist/ReactToastify.css";
// import 'react-toastify/ReactToastify.min.css'
// import { useExcludeHeader } from '@/hooks/useExcludeHeader'
// import { Header } from './component/Header'
// import { Footer } from './component/Footer'


// Other imports and code remain the same...

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '900'],
  display: "swap", // Optional: Ensure consistency across all fonts
});

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '900'],
  display: "swap",
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '900'],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <RQProviders>
        <body className={`${poppins.className} ${nunitoSans.className} ${inter.className}`} >
          <ToastContainer closeOnClick limit={1} />
          <Providers>
            {children}
          </Providers>
        </body>
      </RQProviders>
    </html>
  );
}

