// 'use-client'
import type { Metadata } from "next";
import RQProviders from "@/utils/provider";
import { Poppins, Inter } from "next/font/google";
// import { CookiesProvider } from 'react-cookie';
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "900"], });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <RQProviders>
          <body className={poppins.className}>{children}</body>
        </RQProviders>
    </html>
  );
}
